version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: football_postgres
    environment:
      POSTGRES_USER: football
      POSTGRES_PASSWORD: football
      POSTGRES_DB: football_dw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U football -d football_dw"]
      interval: 5s
      timeout: 5s
      retries: 20

  pipeline:
    build: .
    container_name: football_pipeline
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: football_dw
      DB_USER: football
      DB_PASSWORD: football
    # relance si crash
    restart: "no"

volumes:
  pgdata: